Repository RomiC/rsql-builder, pull requests merged in 2023-05, with the labels that each got.

#281 Bumped min NodeJS version to 16
  .github/workflows/npm-publish.yml
  .github/workflows/npm-test.yml
  package.json
Labels: dx

#282 Changed daily checks to weekly ones
  .github/dependabot.yml
Labels: dx

#288 Fixing existing build issue
  .github/workflows/npm-test.yml
  package-lock.json
  package.json
Labels: bug, dx, dependencies

#278 Expose `Comparison` class
  src/index.ts
  tests/index.spec.ts
Labels: bug
